spring.application.name=neotracker
spring.datasource.url=jdbc:postgresql://localhost:5432/neo_tracker_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
nasa.api.key=${NASA_API_KEY}
nasa.api.base-url=https://api.nasa.gov/neo/rest/v1